name: stroke_order_animator
description: Stroke order animations and quizzes for Chinese characters for use
  in Flutter apps

version: 1.6.1

homepage: https://github.com/Mr-Pepe/stroke-order-animator

repository: https://github.com/Mr-Pepe/stroke-order-animator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  svg_path_parser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
